### ISSUE TITLE
Cannot extract or list files from GOG image of fallout2 

### ISSUE THREAD

**Issue by teacup775** [tomkidd/Extractor#5]
The only message is "error".  (M1 15.1.1) With so little to go on, is there anything else I can do?

**Comment by tomkidd** [comment]
Make sure you're downloading the Offline Game Installers instead of the GOG Galaxy installer

https://www.macsourceports.com/faq#gog_extractor

**Comment by teacup775** [comment]
thank you! will check

**Comment by teacup775** [comment]
that did it. thank you for the very quick reply!

**Comment by tomkidd** [comment]
No problem
